//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SUT.PrintEngine.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StringTable {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringTable() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SUT.PrintEngine.Resources.StringTable", typeof(StringTable).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Abort.
        /// </summary>
        public static string AbortButtonCaption {
            get {
                return ResourceManager.GetString("AbortButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Aborting. Please wait....
        /// </summary>
        public static string AbortingMessage {
            get {
                return ResourceManager.GetString("AbortingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на .
        /// </summary>
        public static string ActiveSlideToolTip {
            get {
                return ResourceManager.GetString("ActiveSlideToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add Payment Transaction.
        /// </summary>
        public static string AddPTTooltip {
            get {
                return ResourceManager.GetString("AddPTTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add Slide.
        /// </summary>
        public static string AddSlideButtonCaption {
            get {
                return ResourceManager.GetString("AddSlideButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add Slide.
        /// </summary>
        public static string AddSlideToolTip {
            get {
                return ResourceManager.GetString("AddSlideToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Align Bottom.
        /// </summary>
        public static string AlignBottomToolTip {
            get {
                return ResourceManager.GetString("AlignBottomToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Align Center.
        /// </summary>
        public static string AlignCenterTextPropertiesToolTip {
            get {
                return ResourceManager.GetString("AlignCenterTextPropertiesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Align Center.
        /// </summary>
        public static string AlignCenterToolTip {
            get {
                return ResourceManager.GetString("AlignCenterToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Align Left.
        /// </summary>
        public static string AlignLeftNodePlacerToolTip {
            get {
                return ResourceManager.GetString("AlignLeftNodePlacerToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Align Left.
        /// </summary>
        public static string AlignLeftTextPropertiesToolTip {
            get {
                return ResourceManager.GetString("AlignLeftTextPropertiesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Align Left.
        /// </summary>
        public static string AlignLeftToolTip {
            get {
                return ResourceManager.GetString("AlignLeftToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Align Middle.
        /// </summary>
        public static string AlignMiddleToolTip {
            get {
                return ResourceManager.GetString("AlignMiddleToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Align/Resize Properties.
        /// </summary>
        public static string AlignResizeToolTip {
            get {
                return ResourceManager.GetString("AlignResizeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Align Right.
        /// </summary>
        public static string AlignRightTextPropertiesToolTip {
            get {
                return ResourceManager.GetString("AlignRightTextPropertiesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Align Right.
        /// </summary>
        public static string AlignRightToolTip {
            get {
                return ResourceManager.GetString("AlignRightToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Align Top.
        /// </summary>
        public static string AlignTopToolTip {
            get {
                return ResourceManager.GetString("AlignTopToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Find a summary of key anti-avoidance information of each country.
        /// </summary>
        public static string AntiAvoidanceDescription {
            get {
                return ResourceManager.GetString("AntiAvoidanceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Anti-Avoidance.
        /// </summary>
        public static string AntiAvoidanceHeader {
            get {
                return ResourceManager.GetString("AntiAvoidanceHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select what you want to print.
        /// </summary>
        public static string AntiAvoidancePrintSelectionHeader {
            get {
                return ResourceManager.GetString("AntiAvoidancePrintSelectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Apply.
        /// </summary>
        public static string ApplyButtonCaption {
            get {
                return ResourceManager.GetString("ApplyButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Apply to all entities.
        /// </summary>
        public static string ApplyToAllCheckBoxCaption {
            get {
                return ResourceManager.GetString("ApplyToAllCheckBoxCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Apply to current items.
        /// </summary>
        public static string ApplyToCurrentItems {
            get {
                return ResourceManager.GetString("ApplyToCurrentItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Arc.
        /// </summary>
        public static string ArcToolTip {
            get {
                return ResourceManager.GetString("ArcToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Both Filled.
        /// </summary>
        public static string ArrowHeadBothFillToolTip {
            get {
                return ResourceManager.GetString("ArrowHeadBothFillToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Both.
        /// </summary>
        public static string ArrowHeadBothToolTip {
            get {
                return ResourceManager.GetString("ArrowHeadBothToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Left Filled.
        /// </summary>
        public static string ArrowHeadLeftFillToolTip {
            get {
                return ResourceManager.GetString("ArrowHeadLeftFillToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Left.
        /// </summary>
        public static string ArrowHeadLeftToolTip {
            get {
                return ResourceManager.GetString("ArrowHeadLeftToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на None.
        /// </summary>
        public static string ArrowHeadNoneToolTip {
            get {
                return ResourceManager.GetString("ArrowHeadNoneToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Right Filled.
        /// </summary>
        public static string ArrowHeadRightFillToolTip {
            get {
                return ResourceManager.GetString("ArrowHeadRightFillToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Right.
        /// </summary>
        public static string ArrowHeadRightToolTip {
            get {
                return ResourceManager.GetString("ArrowHeadRightToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Arrow.
        /// </summary>
        public static string ArrowLineToolTip {
            get {
                return ResourceManager.GetString("ArrowLineToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Arrow.
        /// </summary>
        public static string ArrowToolTip {
            get {
                return ResourceManager.GetString("ArrowToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Auto Arrange On/Off.
        /// </summary>
        public static string AutoArrangeToolTip {
            get {
                return ResourceManager.GetString("AutoArrangeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Balloon Tree Arc Layout.
        /// </summary>
        public static string BalloonTreeArcLayoutToolTip {
            get {
                return ResourceManager.GetString("BalloonTreeArcLayoutToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Balloon Tree Layout.
        /// </summary>
        public static string BalloonTreeLayoutToolTip {
            get {
                return ResourceManager.GetString("BalloonTreeLayoutToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bold.
        /// </summary>
        public static string BoldToolTip {
            get {
                return ResourceManager.GetString("BoldToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Border Color.
        /// </summary>
        public static string BorderColorToolTip {
            get {
                return ResourceManager.GetString("BorderColorToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Branch must have a parent.
        /// </summary>
        public static string BranchMastHaveAParent {
            get {
                return ResourceManager.GetString("BranchMastHaveAParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Branch or Individual.
        /// </summary>
        public static string BranchToolTip {
            get {
                return ResourceManager.GetString("BranchToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bullets.
        /// </summary>
        public static string BulletsTextPropertiesToolTip {
            get {
                return ResourceManager.GetString("BulletsTextPropertiesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Calendar Item.
        /// </summary>
        public static string CalendarMonthViewEditorTitle {
            get {
                return ResourceManager.GetString("CalendarMonthViewEditorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        public static string CancelButtonCaption {
            get {
                return ResourceManager.GetString("CancelButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Center.
        /// </summary>
        public static string CenterNodePlacerToolTip {
            get {
                return ResourceManager.GetString("CenterNodePlacerToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Change.
        /// </summary>
        public static string ChangeButtonCaption {
            get {
                return ResourceManager.GetString("ChangeButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Change Slide.
        /// </summary>
        public static string ChangeSlideButtonCaption {
            get {
                return ResourceManager.GetString("ChangeSlideButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Change Slide.
        /// </summary>
        public static string ChangeSlideComboTitle {
            get {
                return ResourceManager.GetString("ChangeSlideComboTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Chart Options.
        /// </summary>
        public static string ChartControlToolTip {
            get {
                return ResourceManager.GetString("ChartControlToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose an entity.
        /// </summary>
        public static string ChooseAnEntityCaption {
            get {
                return ResourceManager.GetString("ChooseAnEntityCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Collapse operation is not successful due to circular ownership.
        /// </summary>
        public static string CollapseError {
            get {
                return ResourceManager.GetString("CollapseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error in Collapse.
        /// </summary>
        public static string CollapseErrorTitle {
            get {
                return ResourceManager.GetString("CollapseErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Collapse.
        /// </summary>
        public static string CollapseToolTip {
            get {
                return ResourceManager.GetString("CollapseToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Color Picker.
        /// </summary>
        public static string ColorPickerToolTip {
            get {
                return ResourceManager.GetString("ColorPickerToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Color Properties.
        /// </summary>
        public static string ColorPropertiesToolTip {
            get {
                return ResourceManager.GetString("ColorPropertiesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Compact Tree Arc Layout.
        /// </summary>
        public static string CompactTreeArcLayoutToolTip {
            get {
                return ResourceManager.GetString("CompactTreeArcLayoutToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Compact Tree Layout.
        /// </summary>
        public static string CompactTreeLayoutToolTip {
            get {
                return ResourceManager.GetString("CompactTreeLayoutToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create report comparing multiple slides..
        /// </summary>
        public static string CompareReportToolTip {
            get {
                return ResourceManager.GetString("CompareReportToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Compare Slides.
        /// </summary>
        public static string CompareSlideToolTip {
            get {
                return ResourceManager.GetString("CompareSlideToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Configure Entity Label.
        /// </summary>
        public static string ConfigureEntityLabelToolTip {
            get {
                return ResourceManager.GetString("ConfigureEntityLabelToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Are you sure you want to delete?.
        /// </summary>
        public static string ConfirmDelete {
            get {
                return ResourceManager.GetString("ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Copyright © 2010 Orbitax. All right reserved..
        /// </summary>
        public static string CopyrightText {
            get {
                return ResourceManager.GetString("CopyrightText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Copy.
        /// </summary>
        public static string CopyToolTip {
            get {
                return ResourceManager.GetString("CopyToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Corporate tax rate: .
        /// </summary>
        public static string CorporateTaxHeader {
            get {
                return ResourceManager.GetString("CorporateTaxHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на TME does not maintain income tax rates for individuals and unincorporated entities (a default rate equal to the rate that applies to corporations is assumed) and certain foreign countries (a default rate of 0% is assumed). Click here to edit this rate..
        /// </summary>
        public static string CorporateTaxNonSupportedMessage {
            get {
                return ResourceManager.GetString("CorporateTaxNonSupportedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Click the Find Corporate Rates button and choose entities to view their rates..
        /// </summary>
        public static string CorporateTaxSubHeader {
            get {
                return ResourceManager.GetString("CorporateTaxSubHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Corporation.
        /// </summary>
        public static string CorporationToolTip {
            get {
                return ResourceManager.GetString("CorporationToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Corporate Tax Rate.
        /// </summary>
        public static string CorpRatePrintHeader {
            get {
                return ResourceManager.GetString("CorpRatePrintHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Withholding tax rate: .
        /// </summary>
        public static string CrossBorderTaxHeader {
            get {
                return ResourceManager.GetString("CrossBorderTaxHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose The paying entity, one or more receiving countries, a payment stream, then click on the search button..
        /// </summary>
        public static string CrossBorderTaxInputPanelText {
            get {
                return ResourceManager.GetString("CrossBorderTaxInputPanelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на TME does not maintain withholding tax rates for transactions between domestic entities (a default rate of 0% is assumed), individuals and unincorporated entities (a default rate equal to the rate that applies to corporations is assumed) and certain foreign countries (a default rate of 0% is assumed). Click here to edit this rate..
        /// </summary>
        public static string CrossBorderTaxNonSuportedToolTip {
            get {
                return ResourceManager.GetString("CrossBorderTaxNonSuportedToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Click Find Withholding Rates button to choose paying entity, one or more receiving entity(ies) and payment stream for the withholding rates..
        /// </summary>
        public static string CrossBorderTaxSubHeader {
            get {
                return ResourceManager.GetString("CrossBorderTaxSubHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Corporate Structure Book.
        /// </summary>
        public static string CSBookDefaultFileName {
            get {
                return ResourceManager.GetString("CSBookDefaultFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CORPORATE STRUCTURE BOOK.
        /// </summary>
        public static string CSBookDefaultPageTitle {
            get {
                return ResourceManager.GetString("CSBookDefaultPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Generated CS Book.
        /// </summary>
        public static string CSBookFilterStartString {
            get {
                return ResourceManager.GetString("CSBookFilterStartString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create CS Book.
        /// </summary>
        public static string CSBookOpenSaveDialogTitle {
            get {
                return ResourceManager.GetString("CSBookOpenSaveDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CTB must have a parent.
        /// </summary>
        public static string CTBMastHaveAParent {
            get {
                return ResourceManager.GetString("CTBMastHaveAParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на CTB.
        /// </summary>
        public static string CTBToolTip {
            get {
                return ResourceManager.GetString("CTBToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Apply layout style for entire chart..
        /// </summary>
        public static string CurrentLayoutToolTip {
            get {
                return ResourceManager.GetString("CurrentLayoutToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Apply layout style for children of selected parent..
        /// </summary>
        public static string CurrentNodePlacerToolTip {
            get {
                return ResourceManager.GetString("CurrentNodePlacerToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Column name cannot be empty.
        /// </summary>
        public static string CustomColumnEmptyMessage {
            get {
                return ResourceManager.GetString("CustomColumnEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Same column name already exists.
        /// </summary>
        public static string CustomColumnExistingMessage {
            get {
                return ResourceManager.GetString("CustomColumnExistingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please select or type your custom column name.
        /// </summary>
        public static string CustomColumnWindowText {
            get {
                return ResourceManager.GetString("CustomColumnWindowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please type your custom column name.
        /// </summary>
        public static string CustomColumnWindowTextForTaskAndRepository {
            get {
                return ResourceManager.GetString("CustomColumnWindowTextForTaskAndRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cut.
        /// </summary>
        public static string CutToolTip {
            get {
                return ResourceManager.GetString("CutToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel Survey.
        /// </summary>
        public static string DataSurveyCancelSurveyButtonText {
            get {
                return ResourceManager.GetString("DataSurveyCancelSurveyButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Deselect.
        /// </summary>
        public static string DataSurveyContextMenuDeselectAllCells {
            get {
                return ResourceManager.GetString("DataSurveyContextMenuDeselectAllCells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select the entire sheet.
        /// </summary>
        public static string DataSurveyContextMenuSelectAllCells {
            get {
                return ResourceManager.GetString("DataSurveyContextMenuSelectAllCells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select.
        /// </summary>
        public static string DataSurveyContextMenuSelectCells {
            get {
                return ResourceManager.GetString("DataSurveyContextMenuSelectCells", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Continue Survey.
        /// </summary>
        public static string DataSurveyContinueSurveyButtonText {
            get {
                return ResourceManager.GetString("DataSurveyContinueSurveyButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Some of your selection is outside the valid range for the TME survey. TME supports $A$1:$Z$200..
        /// </summary>
        public static string DataSurveyMaxRowColumnExcededMessage {
            get {
                return ResourceManager.GetString("DataSurveyMaxRowColumnExcededMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete.
        /// </summary>
        public static string DeleteToolTip {
            get {
                return ResourceManager.GetString("DeleteToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Text properties cannot be altered here.
        /// </summary>
        public static string DesignerPreferenceTextStyleComment {
            get {
                return ResourceManager.GetString("DesignerPreferenceTextStyleComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit Designer Preferences.
        /// </summary>
        public static string DesignerPreferenceToolTip {
            get {
                return ResourceManager.GetString("DesignerPreferenceToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Disregarded must have a parent.
        /// </summary>
        public static string DisregardedMastHaveAParent {
            get {
                return ResourceManager.GetString("DisregardedMastHaveAParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Disregarded.
        /// </summary>
        public static string DisregardedToolTip {
            get {
                return ResourceManager.GetString("DisregardedToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Done.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Done.
        /// </summary>
        public static string DoneButtonCaption {
            get {
                return ResourceManager.GetString("DoneButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Double Align Left.
        /// </summary>
        public static string DoubleAlignLeftNodePlacerToolTip {
            get {
                return ResourceManager.GetString("DoubleAlignLeftNodePlacerToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Double Side.
        /// </summary>
        public static string DoubleSideNodePlacerToolTip {
            get {
                return ResourceManager.GetString("DoubleSideNodePlacerToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ellipse.
        /// </summary>
        public static string EllipseToolTip {
            get {
                return ResourceManager.GetString("EllipseToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Use the space below to set what shows up in the entity boxes. Add data elements that automatically fill up for that entity by clicking &quot;Insert Entity Data&quot; (these connected fields are highlighted in yellow), or put in your own. By editing the fields below you can also arrange the way the data is shown along with its formatting. .
        /// </summary>
        public static string EntityLabelConfiguratorDescription {
            get {
                return ResourceManager.GetString("EntityLabelConfiguratorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show minimum information in the entity box to speed up the charting.
        /// </summary>
        public static string EntityLabelMode {
            get {
                return ResourceManager.GetString("EntityLabelMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name of an entity cannot be empty.
        /// </summary>
        public static string EntityNameErrorToolTip {
            get {
                return ResourceManager.GetString("EntityNameErrorToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Short name of an entity cannot be empty.
        /// </summary>
        public static string EntityShortNameErrorToolTip {
            get {
                return ResourceManager.GetString("EntityShortNameErrorToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error.
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Validation Required.
        /// </summary>
        public static string ErrorToolTipTitle {
            get {
                return ResourceManager.GetString("ErrorToolTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sorry, TME has encountered an error..
        /// </summary>
        public static string ExceptionHeaderText {
            get {
                return ResourceManager.GetString("ExceptionHeaderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на View technical data.
        /// </summary>
        public static string ExceptionLabel1Text1 {
            get {
                return ResourceManager.GetString("ExceptionLabel1Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hide technical data.
        /// </summary>
        public static string ExceptionLabel1Text2 {
            get {
                return ResourceManager.GetString("ExceptionLabel1Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на sent if you wish to report this problem.
        /// </summary>
        public static string ExceptionLabel2Text1 {
            get {
                return ResourceManager.GetString("ExceptionLabel2Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sent.
        /// </summary>
        public static string ExceptionLabel2Text2 {
            get {
                return ResourceManager.GetString("ExceptionLabel2Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Send feedback.
        /// </summary>
        public static string ExceptionSendButtonTextCompact {
            get {
                return ResourceManager.GetString("ExceptionSendButtonTextCompact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Report this problem.
        /// </summary>
        public static string ExceptionSendButtonTextNormal {
            get {
                return ResourceManager.GetString("ExceptionSendButtonTextNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на There was an error in TME, please help us fix it by reporting this to us..
        /// </summary>
        public static string ExceptionTitleText {
            get {
                return ResourceManager.GetString("ExceptionTitleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Expand.
        /// </summary>
        public static string ExpandToolTip {
            get {
                return ResourceManager.GetString("ExpandToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Export.
        /// </summary>
        public static string ExportButtonCaption {
            get {
                return ResourceManager.GetString("ExportButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exporting spreadsheet please wait....
        /// </summary>
        public static string ExportCommonWaitMsg {
            get {
                return ResourceManager.GetString("ExportCommonWaitMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Export to Doc.
        /// </summary>
        public static string ExportDocButtonCaption {
            get {
                return ResourceManager.GetString("ExportDocButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Export just current slide.
        /// </summary>
        public static string ExportJustCurrenteSlide {
            get {
                return ResourceManager.GetString("ExportJustCurrenteSlide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Export to PDF.
        /// </summary>
        public static string ExportPdfButtonCaption {
            get {
                return ResourceManager.GetString("ExportPdfButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Export.
        /// </summary>
        public static string ExportTitleCaption {
            get {
                return ResourceManager.GetString("ExportTitleCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Office 2003.
        /// </summary>
        public static string ExportTo2003 {
            get {
                return ResourceManager.GetString("ExportTo2003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Office 2007.
        /// </summary>
        public static string ExportTo2007 {
            get {
                return ResourceManager.GetString("ExportTo2007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Export to Excel.
        /// </summary>
        public static string ExportToExcelCommonDialogTitle {
            get {
                return ResourceManager.GetString("ExportToExcelCommonDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The file does not exist, or has been deleted.
        /// </summary>
        public static string FileOpeningFailedMessage {
            get {
                return ResourceManager.GetString("FileOpeningFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fill Color.
        /// </summary>
        public static string FillColorToolTip {
            get {
                return ResourceManager.GetString("FillColorToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fit Entity Size.
        /// </summary>
        public static string FitEntitySizeLabel {
            get {
                return ResourceManager.GetString("FitEntitySizeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fit Entity Size.
        /// </summary>
        public static string FitEntitySizeTooltip {
            get {
                return ResourceManager.GetString("FitEntitySizeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Font Size.
        /// </summary>
        public static string FontSizeTextPropertiesToolTip {
            get {
                return ResourceManager.GetString("FontSizeTextPropertiesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select Font.
        /// </summary>
        public static string FontStyleTextPropertiesToolTip {
            get {
                return ResourceManager.GetString("FontStyleTextPropertiesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Full-screen Off.
        /// </summary>
        public static string FullscreenModeOffTooltip {
            get {
                return ResourceManager.GetString("FullscreenModeOffTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Full-screen.
        /// </summary>
        public static string FullscreenModeOnTooltip {
            get {
                return ResourceManager.GetString("FullscreenModeOnTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Generating Print Preview.
        /// </summary>
        public static string GeneratingPrintPreviewStatusMessage {
            get {
                return ResourceManager.GetString("GeneratingPrintPreviewStatusMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на GET STARTED.
        /// </summary>
        public static string GetStartedButtonContent {
            get {
                return ResourceManager.GetString("GetStartedButtonContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hidden Transaction(s).
        /// </summary>
        public static string HiddenTransactionTitle {
            get {
                return ResourceManager.GetString("HiddenTransactionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hierarchical Arc Layout.
        /// </summary>
        public static string HierarchicalArcLayoutToolTip {
            get {
                return ResourceManager.GetString("HierarchicalArcLayoutToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hierarchical Layout.
        /// </summary>
        public static string HierarchicalLayoutToolTip {
            get {
                return ResourceManager.GetString("HierarchicalLayoutToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на WW Tax Calculator and Optimizer.
        /// </summary>
        public static string HomeAdvanceCalculatorHeader {
            get {
                return ResourceManager.GetString("HomeAdvanceCalculatorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Calculate worldwide tax for current and future years and analyze repatriation and tax minimization strategies..
        /// </summary>
        public static string HomeAdvanceCalculatorText {
            get {
                return ResourceManager.GetString("HomeAdvanceCalculatorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Collaboration.
        /// </summary>
        public static string HomeCollaborationHeader {
            get {
                return ResourceManager.GetString("HomeCollaborationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Organize and store documents online, automatically collect data from around the world and keep track of tax returns and other due dates. .
        /// </summary>
        public static string HomeCollaborationText {
            get {
                return ResourceManager.GetString("HomeCollaborationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Entity Chart.
        /// </summary>
        public static string HomeEntityChart {
            get {
                return ResourceManager.GetString("HomeEntityChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Visually build and maintain your entity chart. Create reports and presentations..
        /// </summary>
        public static string HomeEntityChartPara {
            get {
                return ResourceManager.GetString("HomeEntityChartPara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Research and Compliance.
        /// </summary>
        public static string HomeResearchandComplianceHeader {
            get {
                return ResourceManager.GetString("HomeResearchandComplianceHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Welcome to Tax Management Expert.
        /// </summary>
        public static string HomeWelComeHeader {
            get {
                return ResourceManager.GetString("HomeWelComeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tax Management Expert (TME) is your one-stop shop for all your tax management needs. Please visit www.orbitax.com for information about other international tax products and services by Orbitax..
        /// </summary>
        public static string HomeWelComePara {
            get {
                return ResourceManager.GetString("HomeWelComePara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на HV Tree Arc Layout.
        /// </summary>
        public static string HorVertTreeArcLayoutToolTip {
            get {
                return ResourceManager.GetString("HorVertTreeArcLayoutToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на HV Tree Layout.
        /// </summary>
        public static string HorVertTreeLayoutToolTip {
            get {
                return ResourceManager.GetString("HorVertTreeLayoutToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ignore.
        /// </summary>
        public static string IgnoreButtonCaption {
            get {
                return ResourceManager.GetString("IgnoreButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Import.
        /// </summary>
        public static string ImportButtonCaption {
            get {
                return ResourceManager.GetString("ImportButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The scenario hasn&apos;t been created with the current slide. Do you still want to import entities from current slide?.
        /// </summary>
        public static string ImportEntityChartIntoCalculatorConfirmationMessage {
            get {
                return ResourceManager.GetString("ImportEntityChartIntoCalculatorConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The scenario hasn&apos;t been created with the current slide. Do you still want to import transactions from current slide?.
        /// </summary>
        public static string ImportTransactionsIntoCalculatorConfirmationMessage {
            get {
                return ResourceManager.GetString("ImportTransactionsIntoCalculatorConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Double click to see the slide contents.
        /// </summary>
        public static string InActiveSlideToolTip {
            get {
                return ResourceManager.GetString("InActiveSlideToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Insert Keyword.
        /// </summary>
        public static string InsertKeywordButtonToolTip {
            get {
                return ResourceManager.GetString("InsertKeywordButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You are not connected to internet. Please connect to internet and try again..
        /// </summary>
        public static string InternetErrorDetail {
            get {
                return ResourceManager.GetString("InternetErrorDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Failed to connect to server.
        /// </summary>
        public static string InternetErrorHeader {
            get {
                return ResourceManager.GetString("InternetErrorHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Internet connection problem.
        /// </summary>
        public static string InternetErrorTitle {
            get {
                return ResourceManager.GetString("InternetErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Branch cannot have any child.
        /// </summary>
        public static string InvalidBranchChild {
            get {
                return ResourceManager.GetString("InvalidBranchChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Branch can have only one parent.
        /// </summary>
        public static string InvalidBranchParent {
            get {
                return ResourceManager.GetString("InvalidBranchParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Disregarded can have only one parent.
        /// </summary>
        public static string InvalidDisregardedParent {
            get {
                return ResourceManager.GetString("InvalidDisregardedParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please provide valid email to assign. Each Email addreses must be valid and less than 255 characters.
        /// </summary>
        public static string InvalidEmailAddressForAssignment {
            get {
                return ResourceManager.GetString("InvalidEmailAddressForAssignment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please provide valid email to assign. Each Email addreses must be valid and less than 255 characters. Also Please select Excel cells..
        /// </summary>
        public static string InvalidEmailAddressOrCellsForAssignmen {
            get {
                return ResourceManager.GetString("InvalidEmailAddressOrCellsForAssignmen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email address is not valid.
        /// </summary>
        public static string InvalidEmainAddressErrorToolTip {
            get {
                return ResourceManager.GetString("InvalidEmainAddressErrorToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Receiving percentage not 100%.
        /// </summary>
        public static string InvalidLiquidatePercentage {
            get {
                return ResourceManager.GetString("InvalidLiquidatePercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Deleting entity cannot be a parent or child of any entity.
        /// </summary>
        public static string InvalidOwnershipForDeletingEntity {
            get {
                return ResourceManager.GetString("InvalidOwnershipForDeletingEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Partnership must have minimum two parents.
        /// </summary>
        public static string InvalidPartnership {
            get {
                return ResourceManager.GetString("InvalidPartnership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на RCTB must have minimum two parents.
        /// </summary>
        public static string InvalidRCTB {
            get {
                return ResourceManager.GetString("InvalidRCTB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Third-party entity cannot own 100%.
        /// </summary>
        public static string InvalidThirdpartyOwnership {
            get {
                return ResourceManager.GetString("InvalidThirdpartyOwnership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Italic.
        /// </summary>
        public static string ItalicToolTip {
            get {
                return ResourceManager.GetString("ItalicToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Layouting all slides to {0}.
        /// </summary>
        public static string LayoutAllSlideMessage {
            get {
                return ResourceManager.GetString("LayoutAllSlideMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Layout Slides.
        /// </summary>
        public static string LayoutAllSlideProgressTitle {
            get {
                return ResourceManager.GetString("LayoutAllSlideProgressTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Legend.
        /// </summary>
        public static string LegendToolTip {
            get {
                return ResourceManager.GetString("LegendToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dot Dot Dash.
        /// </summary>
        public static string LinePatternDashDotDot {
            get {
                return ResourceManager.GetString("LinePatternDashDotDot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dot Dash Dash.
        /// </summary>
        public static string LinePatternDashDotDotDot {
            get {
                return ResourceManager.GetString("LinePatternDashDotDotDot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dot Dash.
        /// </summary>
        public static string LinePatternDashDotToolTip {
            get {
                return ResourceManager.GetString("LinePatternDashDotToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dashed.
        /// </summary>
        public static string LinePatternDashedToolTip {
            get {
                return ResourceManager.GetString("LinePatternDashedToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Dotted.
        /// </summary>
        public static string LinePatternDottedToolTip {
            get {
                return ResourceManager.GetString("LinePatternDottedToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Solid.
        /// </summary>
        public static string LinePatternSolidToolTip {
            get {
                return ResourceManager.GetString("LinePatternSolidToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Line Properties.
        /// </summary>
        public static string LinePropertiesToolTip {
            get {
                return ResourceManager.GetString("LinePropertiesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Line.
        /// </summary>
        public static string LineToolTip {
            get {
                return ResourceManager.GetString("LineToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Width 1.
        /// </summary>
        public static string LineWidth1ToolTip {
            get {
                return ResourceManager.GetString("LineWidth1ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Width 2.
        /// </summary>
        public static string LineWidth2ToolTip {
            get {
                return ResourceManager.GetString("LineWidth2ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Width 3.
        /// </summary>
        public static string LineWidth3ToolTip {
            get {
                return ResourceManager.GetString("LineWidth3ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Width 4.
        /// </summary>
        public static string LineWidth4ToolTip {
            get {
                return ResourceManager.GetString("LineWidth4ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Width 5.
        /// </summary>
        public static string LineWidth5ToolTip {
            get {
                return ResourceManager.GetString("LineWidth5ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Width 6.
        /// </summary>
        public static string LineWidth6ToolTip {
            get {
                return ResourceManager.GetString("LineWidth6ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Magnifier.
        /// </summary>
        public static string MagnifyToolTip {
            get {
                return ResourceManager.GetString("MagnifyToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Make Same Height.
        /// </summary>
        public static string MakeSameHeightToolTip {
            get {
                return ResourceManager.GetString("MakeSameHeightToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Make Same Height-Width.
        /// </summary>
        public static string MakeSameSizeBothToolTip {
            get {
                return ResourceManager.GetString("MakeSameSizeBothToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Make Same Size.
        /// </summary>
        public static string MakeSameSizeToolTip {
            get {
                return ResourceManager.GetString("MakeSameSizeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Make Same Width.
        /// </summary>
        public static string MakeSameWidthToolTip {
            get {
                return ResourceManager.GetString("MakeSameWidthToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Navigation.
        /// </summary>
        public static string NavigationToolTip {
            get {
                return ResourceManager.GetString("NavigationToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Percentage cannot be negative.
        /// </summary>
        public static string NegativePercentageError {
            get {
                return ResourceManager.GetString("NegativePercentageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New entity must have a parent.
        /// </summary>
        public static string NewEntityMustHaveAParent {
            get {
                return ResourceManager.GetString("NewEntityMustHaveAParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No.
        /// </summary>
        public static string NoButtonCaption {
            get {
                return ResourceManager.GetString("NoButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This country&apos;s tax rates are not currently maintained in the TME database.
        /// </summary>
        public static string NonSuportedCountryToolTip {
            get {
                return ResourceManager.GetString("NonSuportedCountryToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Note.
        /// </summary>
        public static string NoteToolTip {
            get {
                return ResourceManager.GetString("NoteToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OK.
        /// </summary>
        public static string OkButtonCaption {
            get {
                return ResourceManager.GetString("OkButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;Online Share&gt; .
        /// </summary>
        public static string OnlineRepositoryLinkTooltipPrefix {
            get {
                return ResourceManager.GetString("OnlineRepositoryLinkTooltipPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open.
        /// </summary>
        public static string OpenButtonCaption {
            get {
                return ResourceManager.GetString("OpenButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на or.
        /// </summary>
        public static string OrCaption {
            get {
                return ResourceManager.GetString("OrCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Orthogonal Arc Layout.
        /// </summary>
        public static string OrthogonalArcLayoutToolTip {
            get {
                return ResourceManager.GetString("OrthogonalArcLayoutToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Orthogonal Layout.
        /// </summary>
        public static string OrthogonalLayoutToolTip {
            get {
                return ResourceManager.GetString("OrthogonalLayoutToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Percentage cannot be greater than 100.
        /// </summary>
        public static string OverflowPercentageError {
            get {
                return ResourceManager.GetString("OverflowPercentageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The total holding percentage cannot be greater than 100.
        /// </summary>
        public static string OwnershipPercentageGeaterThan100 {
            get {
                return ResourceManager.GetString("OwnershipPercentageGeaterThan100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The total holding percentage cannot be less than 100.
        /// </summary>
        public static string OwnershipPercentageLessThan100 {
            get {
                return ResourceManager.GetString("OwnershipPercentageLessThan100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0} owns {1}% of {2}.
        /// </summary>
        public static string OwnershipToolTip {
            get {
                return ResourceManager.GetString("OwnershipToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Partnership or Trust.
        /// </summary>
        public static string PartnershipToolTip {
            get {
                return ResourceManager.GetString("PartnershipToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Paste.
        /// </summary>
        public static string PasteToolTip {
            get {
                return ResourceManager.GetString("PasteToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pen.
        /// </summary>
        public static string PenToolTip {
            get {
                return ResourceManager.GetString("PenToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Polygon.
        /// </summary>
        public static string PolygonToolTip {
            get {
                return ResourceManager.GetString("PolygonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Print.
        /// </summary>
        public static string PrintButtonCaption {
            get {
                return ResourceManager.GetString("PrintButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The Selected Printer Is In Error.
        /// </summary>
        public static string PrinterErrorToolTip {
            get {
                return ResourceManager.GetString("PrinterErrorToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Report produced by Tax Management Expert (TME). www.orbitax.com.
        /// </summary>
        public static string PrintFooterText {
            get {
                return ResourceManager.GetString("PrintFooterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Print.
        /// </summary>
        public static string PrintSelectionDialogTitle {
            get {
                return ResourceManager.GetString("PrintSelectionDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The cell is not editable..
        /// </summary>
        public static string ProtectedCellEditError {
            get {
                return ResourceManager.GetString("ProtectedCellEditError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на {0}: {1}, WHT: {2}.
        /// </summary>
        public static string PTToolTip {
            get {
                return ResourceManager.GetString("PTToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на RCTB.
        /// </summary>
        public static string RCTBToolTip {
            get {
                return ResourceManager.GetString("RCTBToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rectangle.
        /// </summary>
        public static string RectangleToolTip {
            get {
                return ResourceManager.GetString("RectangleToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The scenario hasn&apos;t been created with the current slide. Do you want to refresh with current slide?.
        /// </summary>
        public static string RefreshCalculatorScenerioConfirmationMessage {
            get {
                return ResourceManager.GetString("RefreshCalculatorScenerioConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remove Slide.
        /// </summary>
        public static string RemoveSlideToolTip {
            get {
                return ResourceManager.GetString("RemoveSlideToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Repository.
        /// </summary>
        public static string RepositoryHeader {
            get {
                return ResourceManager.GetString("RepositoryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Repository.
        /// </summary>
        public static string RepositoryPrintHeader {
            get {
                return ResourceManager.GetString("RepositoryPrintHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create, delete and modify your attachments..
        /// </summary>
        public static string RepositorySubHeader {
            get {
                return ResourceManager.GetString("RepositorySubHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Column name is reserved.
        /// </summary>
        public static string ReservedComunNameErrorMessage {
            get {
                return ResourceManager.GetString("ReservedComunNameErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Decrease Size.
        /// </summary>
        public static string ResizeDecreaseSizeToolTip {
            get {
                return ResourceManager.GetString("ResizeDecreaseSizeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Resize chart to fit slide.
        /// </summary>
        public static string ResizeExportedChartToFitSlide {
            get {
                return ResourceManager.GetString("ResizeExportedChartToFitSlide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Increase Size.
        /// </summary>
        public static string ResizeIncreaseSizeToolTip {
            get {
                return ResourceManager.GetString("ResizeIncreaseSizeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Retry.
        /// </summary>
        public static string RetryButtonCaption {
            get {
                return ResourceManager.GetString("RetryButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rule details.
        /// </summary>
        public static string RuleDetailsPrintRadioText {
            get {
                return ResourceManager.GetString("RuleDetailsPrintRadioText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rule summaries.
        /// </summary>
        public static string RuleSummaryPrintRadioText {
            get {
                return ResourceManager.GetString("RuleSummaryPrintRadioText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save.
        /// </summary>
        public static string SaveButtonCaption {
            get {
                return ResourceManager.GetString("SaveButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save project.
        /// </summary>
        public static string SaveConfirmHeader {
            get {
                return ResourceManager.GetString("SaveConfirmHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You have unsaved data, do you want to save project?.
        /// </summary>
        public static string SaveConfirmMessage {
            get {
                return ResourceManager.GetString("SaveConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Survey has saved as template..
        /// </summary>
        public static string SaveSurveyAsTemplateMessage {
            get {
                return ResourceManager.GetString("SaveSurveyAsTemplateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search Next.
        /// </summary>
        public static string SearchNextToolTip {
            get {
                return ResourceManager.GetString("SearchNextToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No match.
        /// </summary>
        public static string SearchNoMatch {
            get {
                return ResourceManager.GetString("SearchNoMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show search option.
        /// </summary>
        public static string SearchOptionCollapsedButtonCaption {
            get {
                return ResourceManager.GetString("SearchOptionCollapsedButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hide search option.
        /// </summary>
        public static string SearchOptionExpandedButtonCaption {
            get {
                return ResourceManager.GetString("SearchOptionExpandedButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search option.
        /// </summary>
        public static string SearchOptionExpanderHeader {
            get {
                return ResourceManager.GetString("SearchOptionExpanderHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search Previous.
        /// </summary>
        public static string SearchPreviousToolTip {
            get {
                return ResourceManager.GetString("SearchPreviousToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show search result.
        /// </summary>
        public static string SearchResultCollapsedButtonCaption {
            get {
                return ResourceManager.GetString("SearchResultCollapsedButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hide search result.
        /// </summary>
        public static string SearchResultExpandedButtonCaption {
            get {
                return ResourceManager.GetString("SearchResultExpandedButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search result.
        /// </summary>
        public static string SearchResultHeader {
            get {
                return ResourceManager.GetString("SearchResultHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search.
        /// </summary>
        public static string SearchToolTip {
            get {
                return ResourceManager.GetString("SearchToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select All.
        /// </summary>
        public static string SelectAllToolTip {
            get {
                return ResourceManager.GetString("SelectAllToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select layout style for entire chart..
        /// </summary>
        public static string SelectLayoutToolTip {
            get {
                return ResourceManager.GetString("SelectLayoutToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select layout style for children of selected parent..
        /// </summary>
        public static string SelectNodePlacerToolTip {
            get {
                return ResourceManager.GetString("SelectNodePlacerToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Set as default.
        /// </summary>
        public static string SetAsDefaultButtonCaption {
            get {
                return ResourceManager.GetString("SetAsDefaultButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Problem connecting to online share, TME will start without the collaboration feature now..
        /// </summary>
        public static string SharepointServerNotFound {
            get {
                return ResourceManager.GetString("SharepointServerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show/Hide Payment Transactions.
        /// </summary>
        public static string ShowHidePTToolTip {
            get {
                return ResourceManager.GetString("ShowHidePTToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Showing Transaction(s).
        /// </summary>
        public static string ShowingTransactionTitle {
            get {
                return ResourceManager.GetString("ShowingTransactionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Single Top.
        /// </summary>
        public static string SingleTopNodePlacerToolTip {
            get {
                return ResourceManager.GetString("SingleTopNodePlacerToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Click here to edit slide title..
        /// </summary>
        public static string SlideLabelToolTip {
            get {
                return ResourceManager.GetString("SlideLabelToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Change Slide for All Tabs.
        /// </summary>
        public static string SlideSelectorHeading {
            get {
                return ResourceManager.GetString("SlideSelectorHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Smooth Polygon.
        /// </summary>
        public static string SmoothPolygonToolTip {
            get {
                return ResourceManager.GetString("SmoothPolygonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sort slides.
        /// </summary>
        public static string SortSlidesToolTip {
            get {
                return ResourceManager.GetString("SortSlidesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на + Add Item.
        /// </summary>
        public static string SplitedNumberEditorAddItem {
            get {
                return ResourceManager.GetString("SplitedNumberEditorAddItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Entity Data.
        /// </summary>
        public static string SSTPrintHeader {
            get {
                return ResourceManager.GetString("SSTPrintHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Stagger.
        /// </summary>
        public static string StaggerNodePlacerToolTip {
            get {
                return ResourceManager.GetString("StaggerNodePlacerToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Survey record will be deleted. To delete associated files and folders please delete from repository..
        /// </summary>
        public static string SurveyDeleteConfirmMsg {
            get {
                return ResourceManager.GetString("SurveyDeleteConfirmMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Are you sure you want to cancel the survey?.
        /// </summary>
        public static string SurveyEditorCloseConfirmMessage {
            get {
                return ResourceManager.GetString("SurveyEditorCloseConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel Survey.
        /// </summary>
        public static string SurveyEditorCloseConfirmTitle {
            get {
                return ResourceManager.GetString("SurveyEditorCloseConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Survey Templete record will be deleted. To delete associated files and folders please delete from repository.
        /// </summary>
        public static string SurveyTemplateDeleteConfirmMsg {
            get {
                return ResourceManager.GetString("SurveyTemplateDeleteConfirmMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exporting spreadsheet please wait....
        /// </summary>
        public static string TaskExportWaitMsg {
            get {
                return ResourceManager.GetString("TaskExportWaitMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Task Manager.
        /// </summary>
        public static string TaskHeader {
            get {
                return ResourceManager.GetString("TaskHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Task manager.
        /// </summary>
        public static string TaskManagerPrintHeader {
            get {
                return ResourceManager.GetString("TaskManagerPrintHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Create, delete and modify your tasks..
        /// </summary>
        public static string TaskSubHeader {
            get {
                return ResourceManager.GetString("TaskSubHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Assuming you can make an intercompany payment, select the payment stream and the receiving entity.
        /// </summary>
        public static string TCInterCompanyPaymentLabel {
            get {
                return ResourceManager.GetString("TCInterCompanyPaymentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Text Properties.
        /// </summary>
        public static string TextPropertiesToolTip {
            get {
                return ResourceManager.GetString("TextPropertiesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A third party cannot be owned by another entity.
        /// </summary>
        public static string ThirdPartyCannotBeOwnedByOthers {
            get {
                return ResourceManager.GetString("ThirdPartyCannotBeOwnedByOthers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Third Party.
        /// </summary>
        public static string ThirdPartyToolTip {
            get {
                return ResourceManager.GetString("ThirdPartyToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tree Arc Layout.
        /// </summary>
        public static string TreeArcLayoutToolTip {
            get {
                return ResourceManager.GetString("TreeArcLayoutToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tree Layout.
        /// </summary>
        public static string TreeLayoutToolTip {
            get {
                return ResourceManager.GetString("TreeLayoutToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Use the space below to set what shows up in the entity boxes. Add data elements that automatically fill up for that entity by clicking &quot;Insert Entity Data&quot; (these connected fields are highlighted in yellow), or put in your own. By editing the fields below you can also arrange the way the data is shown along with its formatting. .
        /// </summary>
        public static string TSSTLabelConfiguratorDescription {
            get {
                return ResourceManager.GetString("TSSTLabelConfiguratorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Underlined.
        /// </summary>
        public static string UnderlinedToolTip {
            get {
                return ResourceManager.GetString("UnderlinedToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please wait....
        /// </summary>
        public static string WaitScreenMessage {
            get {
                return ResourceManager.GetString("WaitScreenMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Withholding Tax Rate.
        /// </summary>
        public static string WithHoldingPrintHeader {
            get {
                return ResourceManager.GetString("WithHoldingPrintHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Withholding tax rate details for {0} paying {1}.
        /// </summary>
        public static string WithHoldingRateDetailText {
            get {
                return ResourceManager.GetString("WithHoldingRateDetailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Yes.
        /// </summary>
        public static string YesButtonCaption {
            get {
                return ResourceManager.GetString("YesButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Zoom.
        /// </summary>
        public static string ZoomControlToolTip {
            get {
                return ResourceManager.GetString("ZoomControlToolTip", resourceCulture);
            }
        }
    }
}
